export default {
  /*
  * common
  * COMMON_CONFIRM_REQUEST:
  * COMMON_CONFIRM_SUCCESS:
  * COMMON_CONFIRM_FAILURE:
  *  */

  COMMON_CONFIRM_REQUEST: 'COMMON_CONFIRM_REQUEST',
  COMMON_CONFIRM_SUCCESS: 'COMMON_CONFIRM_SUCCESS',
  COMMON_CONFIRM_FAILURE: 'COMMON_CONFIRM_FAILURE',
}
